# Change these first
owner: quizilkend # Your GitHub organization or username, where this repository lives
repo: balkonien_uptime # The name of this repository
title: quizilkend
user-agent: quizilkend

sites:
  - name: balkonien main
    url: https://balkonien.org
  - name: balkonien yunohost
    url: https://yunohost.balkonien.org
  - name: Greiner.schule
    url: https://greiner.schule

assignees:
  - quizilkend

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /balkonien_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Samuels Uptimes
  introTitle: "*Hier werden die Downtimes folgender Webseiten mit Upptime getrackt."
  introMessage: Hier gibt es eine knappe Übersicht von Samuels Seiten und deren Status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
